### ISSUE TITLE
Example Notebook does not work

### ISSUE THREAD

**Issue by apahl** [jparkhill/TensorMol#11]
Hi, I am really curious to try this package out and want to run some example notebooks.

The example notebook *Simple Geometry Optimization And Harmonic Analysis* does not work.  
It gives a `FileNotFoundError` in cell 2:

`FileNotFoundError: [Errno 2] No such file or directory: './datasets/david_test.xyz'`

I am trying this on Ubuntu 17.10 with Python 3.6 in Anaconda.

Kind regards,
Axel

**Comment by jparkhill** [comment]
Axel - 
   This morning we updated the readme with a link to a set of trained networks, and /samples/test_tensormol01.py which shows how to reproduce the data from the arxiv paper. I should probably clear out all the old developmental scripts to help avoid confusion, but we tend to revise things pretty rapidly. 

Thanks for your interest, if you have any difficulties using test_tensormol01.py don't hesitate to reach out. 

Best- 
John

**Comment by apahl** [comment]
Hi John,

thanks, I will try that.

Thanks again for this great and very promising package.

Axel.
