### ISSUE TITLE
Tensorflow version requirement 1.1

### ISSUE THREAD

**Issue by stefdoerr** [jparkhill/TensorMol#13]
You can put in the docs that you need 1.1. Does not work with 1.4 as 
```
ValueError: `tf.add_check_numerics_ops() is not compatible with TensorFlow control flow operations such as `tf.cond()` or `tf.while_loop()`
```

**Comment by jparkhill** [comment]
Stefan - 
   I removed the numeric check ops and tested it's working in 1.4.
   Pretty bizzare google chose to break this compatibility which existed in < 1.3...

anyways, thanks for bringing it to my attention.

**Comment by stefdoerr** [comment]
Thanks!
