### ISSUE TITLE
Issues with starting up:

### ISSUE THREAD

**Issue by naturalabundance** [jparkhill/TensorMol#27]
I installed TF & installed TM on an Ubuntu VM. I have tried to import TensorMol as tm and receive 

NameError: name 'sys' is not defined 

I received this error with "python test.py" commands as well. Please advise!

**Comment by jparkhill** [comment]
a) Don't execute python test.py use: "python ./samples/test_chemspider9.py"

b) sys is an important package which is contained in all Unix python distributions. First try "import sys" at an ordinary python prompt. If that doesn't work then basically your python distribution is not functional...

**Comment by naturalabundance** [comment]
The import sys was working when I ran it from command line, but not when was failing when I tried to import TensorMol or tried to execute any of the samples. I found that adding it explicitly to the .py files remedied this problem. Thank you for your help Dr. Parkhill!

**Comment by PaoloBenigni** [comment]
Can you comment on which packages required specifying sys for?
