### ISSUE TITLE
InvalidArgumentError while running test.py

### ISSUE THREAD

**Issue by nivedita104** [jparkhill/TensorMol#38]
Hi,

I could install successfully TensorMol package. I tried running the test.py file in the sample folder. I got the following error:
InvalidArgumentError (see above for traceback): Got info = 2 for batch index 0, expected info = 0. Debug_info = heevd
         [[Node: SelfAdjointEigV2 = SelfAdjointEigV2[T=DT_DOUBLE, compute_v=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](add_4)]]
         [[Node: add_19/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_284_add_19", tensor_type=DT_DOUBLE, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

What should I do to rectify this?
Would appreciate any help on this.

Thanks,
Nivl

**Comment by jeherr** [comment]
Unfortunately TensorMol is no longer being developed.
