### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by xiexr151e** [jparkhill/TensorMol#9]
When attempting to even import TensorMol on the Python interpretor, the Python interpretor complains about inconsistent use of tabs and spaces. The error occurs at line 282 in QuasiNewtonTools.py, but I know I've seen more inconsistent uses of tabs and spaces elsewhere (for example, in test_h2o.py).

**Comment by jparkhill** [comment]
Thanks for bringing this to my attention, I fixed the instances in those two files
All the developers are still using python2.7X, so you'll have better luck with that.

**Comment by xiexr151e** [comment]
I just have a question, regarding your tutorial document and the pre-trained neural networks provided in the README. 
It occurred to me that the program wants a *.tfm file, while the downloaded file was a *.tfn file, and also the names in the tutorial and the neural network file does not match. Is the intended file in the tutorial "Mol_H2O_wb97xd_1to21_with_prontonated_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100_rightalpha_nodropout"?

**Comment by xiexr151e** [comment]
Hello again,
The build from yesterday allowed me to execute this package, but if I reinstall it, it states that there is no module named MolEmb. Were there any changes made...?

**Comment by kunkinger** [comment]
Hello Derek,

Unzip the networks.tar.gz should produce a folder named "networks" that
contains following files and folders:


*chemspider12_nosolvation.tfm*

*Mol_chemspider12_maxatom35_H2O_with_CH4_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100_rightalpha.tfn*

*Mol_chemspider12_maxatom35_H2O_with_CH4_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100_rightalpha*

*chemspider12_solvation.tfm*

*Mol_chemspider12_clean_maxatom35_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100.tfn*

*Mol_chemspider12_clean_maxatom35_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100*

*water_network.tfm*

*Mol_H2O_wb97xd_1to21_with_prontonated_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100_rightalpha_nodropout.tfn*

*Mol_H2O_wb97xd_1to21_with_prontonated_ANI1_Sym_Direct_RawBP_EE_ChargeEncode_Update_vdw_DSF_elu_Normalize_Dropout_act_sigmoid100_rightalpha_nodropout*


We have renamed the .tfm files for easy understanding. You just need to
move these files and folders into the "networks" folder in your TensorMol
folder, then you should be able to run the test_tensormol01.py .

I  do not think there  is any change made to MolEmb.  You should have the
MolEmb.so file in your TensorMol folder after you execute  "sudo pip
install -e . " in the TensorMol home folder.  If you have any questions, I
will be happy to answer them

-Best,

Kun

**Comment by xiexr151e** [comment]
Are there any specific requirements for the input files?
I am trying to test the module with my own input (it's just an xyz file with 10 identical water molecules), but I get this error:

ValueError: zero-size array to reduction operation maximum which has no identity

This is from TensorMolData.py, line 1233, in __init__:
    self.MaxNAtoms = np.max([m.NAtoms() for m in self.set.mols])

To which it calls upon a numpy function.

**Comment by kunkinger** [comment]
The second line of your xyz file needs start with string "Comment:".
Such as:
3
Comment: single water
O  0 0 0
H  0 0 -1
H  0 0 1

**Comment by jparkhill** [comment]
Actually Kun and Derek, I just eliminated this limitation from the package, just ordinary xyz's should work now, as long as all atom names are characters. 

Best- 
John

**Comment by xiexr151e** [comment]
Hello again,

May I ask what are the units you used for the energy output in your calculations (from EnAndForce)?
For a water monomer, we get -.0023 from TensorMol.

**Comment by kunkinger** [comment]
As now mentioned in the tutorial [](http://tensormol.readthedocs.io/en/latest/Tutorials.html#units)
the energy is given in Hartrees. The zero of energy is the average atomization energy of the set used to train that network.

**Comment by xiexr151e** [comment]
Hello,

Is there a way to directly feed XYZ input into energy calculation functions, rather than using ReadXYZ()?

**Comment by jordangarside** [comment]
@xiexr151e 
molecule   = Mol()
molecule.atoms    = atoms # an array of atomic charges
molecule.coords   = atomic_coords # an [atomCount x 3] array of positions

**Comment by jparkhill** [comment]
if En(m) returns the energy given a molecule and the atoms are "atoms"
EnergyFunctionOfCoords=lambda X: En(Mol(atoms,X))

**Comment by xiexr151e** [comment]
So, no need to pass in the symbols?

**Comment by jeherr** [comment]
No the molecule.atoms variable goes by atomic number. So molecule.atoms = np.array([1, 1, 8]) would work for a water molecule. molecule.coords is just the xyz (no atomic number or symbol) in the same order as molecule.atoms.

**Comment by xiexr151e** [comment]
I have a few more questions:
Regarding the water network, is it possible to do calculations outside of the TensorMol directory and not move the huge water network dataset depending on where I run the script? I am attempting to write some scripts on my own, and I wish to not move the network file to different directories.
